# Generated by Django 2.1.7 on 2019-03-22 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 21, 44, 94044, tzinfo=utc))),
                ('group', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=150)),
                ('contact', models.IntegerField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 21, 44, 94792, tzinfo=utc))),
                ('group', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=150)),
                ('contact', models.IntegerField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
