# Generated by Django 2.1.7 on 2019-03-22 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptors',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 28, 9, 942555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donors',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 28, 9, 943230, tzinfo=utc)),
        ),
    ]
