# Generated by Django 2.1.7 on 2019-03-22 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_auto_20190322_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptor',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='acceptor',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
