# Generated by Django 2.1.7 on 2019-03-22 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_auto_20190322_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptor',
            old_name='status',
            new_name='attended',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='status',
            new_name='attended',
        ),
        migrations.AlterField(
            model_name='acceptor',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 30, 58, 650156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 30, 58, 650767, tzinfo=utc)),
        ),
    ]
